services:
  - type: web
    name: rsshub
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: TWITTER_API_AUTH
        value: "false"
      - key: USE_TWITTER_SCRAPER
        value: "true"
      - key: WHITELIST
        value: "/twitter/user/:id"
