services:
  - type: web
    name: rsshub
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: CACHE_TYPE
        value: memory
